# Generated by Django 5.2.8 on 2026-01-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='title',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='email',
            field=models.EmailField(default='exampleEmail@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='facebook',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='footer_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='gym_address',
            field=models.TextField(default='default image', max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='instagram',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='main_bg_image',
            field=models.ImageField(default='hgsd', upload_to='site_info_media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='membershi_plan',
            field=models.JSONField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='phone1',
            field=models.BigIntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='phone2',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='twitter',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='youtube',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
