# Generated by Django 5.2.8 on 2026-02-10 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_siteinfo_description_remove_siteinfo_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=250)),
                ('highlights', models.TextField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GymGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gym_gallery/')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiveUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=300)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='phone2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EventFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='event_photos/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.events')),
            ],
        ),
        migrations.CreateModel(
            name='LiveUpdateFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='live_update_files/')),
                ('live_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.liveupdates')),
            ],
        ),
    ]
