# Generated by Django 5.2.8 on 2026-02-11 07:55

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_events_gymgallery_liveupdates_alter_siteinfo_phone2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfiles',
            name='file',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='event_photos/'),
        ),
        migrations.AlterField(
            model_name='gymgallery',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='gym_gallery/'),
        ),
        migrations.AlterField(
            model_name='liveupdatefiles',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='live_update_files/'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='main_bg_image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='site_info_media/'),
        ),
    ]
