# Generated by Django 6.0.2 on 2026-02-18 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_eventfiles_file_alter_gymgallery_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liveupdates',
            options={'ordering': ['-last_modified']},
        ),
        migrations.AddField(
            model_name='liveupdates',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='eventfiles',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_files', to='core.events'),
        ),
        migrations.AlterField(
            model_name='liveupdatefiles',
            name='live_update',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liveupdates_files', to='core.liveupdates'),
        ),
    ]
