# Generated by Django 6.0.2 on 2026-02-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_liveupdates_options_liveupdates_last_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveupdatefiles',
            name='file',
            field=models.FileField(upload_to='live_update_files/'),
        ),
    ]
