# Generated by Django 6.0.2 on 2026-02-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_liveupdatefiles_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveupdatefiles',
            name='file',
            field=models.FileField(upload_to='live_update_files/'),
        ),
    ]
