# Generated by Django 6.0.2 on 2026-02-18 12:38

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_liveupdatefiles_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveupdatefiles',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='live_update_files/'),
        ),
    ]
