# Generated by Django 6.0.2 on 2026-02-19 04:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_liveupdatefiles_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveupdatefiles',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
