# Generated by Django 6.0.2 on 2026-02-19 06:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_liveupdatefiles_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymgallery',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
