# Generated by Django 6.0.2 on 2026-02-19 06:46

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_gymgallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfiles',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
